version: '2'
services:
  web:
    build: .
    command: ./script/start
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /bundle
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
