#!/bin/bash

# Install gems if necessary
bundle check || bundle install

# Sometimes this file doesn't get cleaned up when the container exits
rm -f tmp/pids/server.pid

bundle exec rails s -b 0.0.0.0
